version: "3.8"
services:
  controller:
    container_name: controller
    image: ngrinder/controller:3.5.8
    environment:
      - TZ=Asia/Seoul
    restart: always
    ports:
      - "8880:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    volumes:
      - ./ngrinder-controller:/opt/ngrinder-controller
    sysctls:
      - net.core.somaxconn=65000
  agent-1:
    container_name: agent-1
    image: ngrinder/agent:3.5.8
    environment:
      - TZ=Asia/Seoul
    restart: always
    links:
      - controller
    sysctls:
      - net.core.somaxconn=65000
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc:
        soft: 1024000
        hard: 1024000
      nofile:
        soft: 1024000
        hard: 1024000
