version: "3.8"

networks:
  k6:
  grafana:

services:
  influxdb:
    image: influxdb:1.8
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    # volumes:
    # - influxdb_data:/bitnami/influxdb

  grafana:
    image: grafana/grafana:9.3.8
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
    links:
      - influxdb
    #volumes:
    # - ./grafana:/etc/grafana/provisioning/

  k6:
    image: grafana/k6:latest
    networks:
      - k6
    ports:
      - 6565:6565
    environment:
      - K6_INFLUXDB_USERNAME=admin
      - K6_INFLUXDB_PASSWORD=adminadmin
      - K6_OUT=influxdb=http://host.docker.internal:8086/k6
    volumes:
      - ./examples:/scripts
    #command:
volumes:
  grafana:
  influxdb:
